create database mydatabase ;

use mydatabase ;

select * from customer 
where review_rating is null ;

-- 1) What is the total revenue generated by male or felmale cusgtomers ?

select gender , sum(purchase_amount) as revnue
from customer
group by gender ; 

-- 2) which coustomers used a discount but still spent more the average purchase amount ?

select customer_id, purchase_amount  ,discount_applied 
from customer
where  discount_applied  = "yes" and purchase_amount >  (select avg(purchase_amount) from customer); 

-- 3) which are top 5 product with the highest avg review rating

select item_purchased, round(avg(review_rating),2)  as avg_review_rating
from customer
group by item_purchased
order by avg_review_rating  desc
limit 5 ; 

-- 4) compare the avg purchase amount between standard and Express shipping .?

select shipping_type,  round(avg(purchase_amount),2)  as avg_purchase_amount
from customer 
where shipping_type in ("Standard","Express")
group by shipping_type ;

-- 5) Do subscriced customers  spend more ? compare avg spend and total revenue between subscricebers and non-subscricebers

select  subscription_status,
count(customer_id) as total_customers ,
round(avg(purchase_amount),2)  as avg_spend,
round(sum(purchase_amount),2)  as total_revenue_spent
from customer 
group by subscription_status 
order by avg_spend, total_revenue_spent desc ;

-- 6) which 5 products have the highest percentage of purchases with discounts applied ?


select item_purchased,
(100.0 * sum(CASE when discount_applied = 'Yes' Then 1 Else 0 End)/ count(*) ) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5 ; -- 100 * (2 / 3) = 66.67%

-- 7) what are top 3 msot purchased products within each category 

with item_count as (

select category, item_purchased ,count(customer_id) as total_order,
row_number() over (partition by category order by count(customer_id) desc ) as item_rank
from customer 
group by category, item_purchased )

select item_rank, category, item_purchased,  total_order
from item_count
where item_rank <= 3;

-- 8) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status ; 

-- 9)  what is the revenue contribution of each age_group 

/*select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group  
order by total_revenue desc ;*/

SELECT 
  age_group,
  SUM(purchase_amount) AS total_revenue,
  (100.0 * SUM(purchase_amount) / SUM(SUM(purchase_amount)) OVER ()) AS revenue_percentage
FROM customer
GROUP BY age_group
ORDER BY revenue_percentage DESC;





